version: '3'
services:
  postgres_pl:
    container_name: postgres_pl
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres_pl:/data
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - '5433:5432'
    networks:
      - network-portal_lamia
  api-portal_lamia:
    build:
      context: '.'
      dockerfile: Dockerfile.dev
    container_name: api-portal_lamia
    command: yarn start:debug
    env_file:
      - .env
    environment:
      TYPEORM_PORT: 5432
      TYPEORM_HOST: postgres_pl
      STORAGE_DRIVER: disk
    ports:
      - '${PORT}:3333'
      - '9229:9229'
    networks:
      - network-portal_lamia
    depends_on:
      - postgres_pl
    volumes:
      - ./:/app/

volumes:
  postgres_pl:

networks:
  network-portal_lamia:
    driver: bridge