name: 'API LAMIA'
on:
  push:
    branches:
      - hml
    paths:
      - "./**"

  pull_request:
    branches: 
      - hml
    paths:
      - "./**"

jobs:
  docker:
    name: 'API LAMIA'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./
        shell: bash

    steps:

      - if: github.event_name == 'pull_request'
        name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}

      - name: Check Out Repo
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2

      - name: Login to Docker hub
        if: github.event_name == 'pull_request'
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        if: github.event_name == 'pull_request'
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        if: github.event_name == 'pull_request'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/container